{
	TFile d1("results_LBRT.root");
	TFile d2("results_LTRB.root");
	TCanvas MyC;
	gPad->SetLogy();
	auto d1p0=d1.Get<TH1F>("theta_x_star_left_right_proj;1");
	auto d1p1=d1.Get<TH1F>("theta_x_star_left_right_cut1_proj;1");
	auto d1p2=d1.Get<TH1F>("theta_x_star_left_right_cut2_proj;1");
	auto d1p3=d1.Get<TH1F>("theta_x_star_left_right_cut3_proj;1");
	auto d1p4=d1.Get<TH1F>("theta_x_star_left_right_cut4_proj;1");
	auto d2p0=d2.Get<TH1F>("theta_x_star_left_right_proj;1");
	auto d2p1=d2.Get<TH1F>("theta_x_star_left_right_cut1_proj;1");
	auto d2p2=d2.Get<TH1F>("theta_x_star_left_right_cut2_proj;1");
	auto d2p3=d2.Get<TH1F>("theta_x_star_left_right_cut3_proj;1");
	auto d2p4=d2.Get<TH1F>("theta_x_star_left_right_cut4_proj;1");
	d1p0->SetTitle("Left-right difference in #theta_{x} (diagonal LBRT);#theta_{x,left}-#theta_{x,right} (#mu rad)");
	d2p0->SetTitle("Left-right difference in #theta_{x} (diagonal LTRB);#theta_{x,left}-#theta_{x,right} (#mu rad)");
	d1p0->GetXaxis()->SetRangeUser(-250.,125.);
	d2p0->GetXaxis()->SetRangeUser(-350.,30.);
	d1p1->SetLineColor(kGreen);
	d1p2->SetLineColor(kBlue);
	d1p3->SetLineColor(kMagenta);
	d1p4->SetLineColor(kRed);
	d2p1->SetLineColor(kGreen);
	d2p2->SetLineColor(kBlue);
	d2p3->SetLineColor(kMagenta);
	d2p4->SetLineColor(kRed);
	TLegend leg(0.1,0.65,0.3,0.9);
	leg.AddEntry(d1p0,"No cut","lep");
	leg.AddEntry(d1p1,"Cut 1","lep");
	leg.AddEntry(d1p2,"Cuts 1+2","lep");
	leg.AddEntry(d1p3,"Cuts 1+2+3","lep");
	leg.AddEntry(d1p4,"Cuts 1+2+3+4","lep");
	d1p0->Draw();
	leg.Draw();
	d1p1->Draw("same");
	d1p2->Draw("same");
	d1p3->Draw("same");
	d1p4->Draw("same");
	MyC.Print("thetaX-LR-diag1R-r585-14p61millionEvt.pdf");
	MyC.Print("thetaX-LR-diag1R-r585-14p61millionEvt.png");
	TLegend leg2(0.1,0.65,0.3,0.9);
	leg2.AddEntry(d2p0,"No cut","lep");
	leg2.AddEntry(d2p1,"Cut 1","lep");
	leg2.AddEntry(d2p2,"Cuts 1+2","lep");
	leg2.AddEntry(d2p3,"Cuts 1+2+3","lep");
	leg2.AddEntry(d2p4,"Cuts 1+2+3+4","lep");
	d2p0->Draw();
	leg2.Draw();
	d2p1->Draw("same");
	d2p2->Draw("same");
	d2p3->Draw("same");
	d2p4->Draw("same");
	MyC.Print("thetaX-LR-diag2R-r585-14p61millionEvt.pdf");
	MyC.Print("thetaX-LR-diag2R-r585-14p61millionEvt.png");
}
