{
	TFile d1("results_LBRT.root");
	TFile d2("results_LTRB.root");
	TCanvas MyC;
	gPad->SetLogz();
	auto* xyl1=d1.Get<TH2F>("x_right_near_y_right_near;1");
	auto* xyl2=d2.Get<TH2F>("x_right_near_y_right_near;1");
	xyl1->SetTitle("X vs Y, right near (diagonal LBRT);X_{R,nr} (mm);Y_{R,nr}");
	xyl2->SetTitle("X vs Y, right near (diagonal LTRB);X_{R,nr} (mm);Y_{R,nr}");
	xyl1->GetXaxis()->SetRangeUser(-30.,30.);
	xyl2->GetXaxis()->SetRangeUser(-30.,30.);
	xyl1->GetYaxis()->SetRangeUser(0.,30.);
	xyl2->GetYaxis()->SetRangeUser(-30.,-0.);
	auto* xyl1b=d1.Get<TH2F>("x_right_near_y_right_near_cut3;1");
	auto* xyl2b=d2.Get<TH2F>("x_right_near_y_right_near_cut3;1");
	xyl1b->SetTitle("X vs Y, right near (diagonal LBRT+cuts 1-2-3);X_{R,nr} (mm);Y_{R,nr}");
	xyl2b->SetTitle("X vs Y, right near (diagonal LTRB+cuts 1-2-3);X_{R,nr} (mm);Y_{R,nr}");
	xyl1b->GetXaxis()->SetRangeUser(-30.,30.);
	xyl2b->GetXaxis()->SetRangeUser(-30.,30.);
	xyl1b->GetYaxis()->SetRangeUser(0.,30.);
	xyl2b->GetYaxis()->SetRangeUser(-30.,-0.);
	xyl1->Draw("colz");
	MyC.Print("xNear-yNear-diag1R-LBRT-r369596v17-alignOnRealGeom-2MEvts.pdf");
	MyC.Print("xNear-yNear-diag1R-LBRT-r369596v17-alignOnRealGeom-2MEvts.png");
	xyl2->Draw("colz");
	MyC.Print("xNear-yNear-diag2R-LTRB-r369596v17-alignOnRealGeom-2MEvts.pdf");
	MyC.Print("xNear-yNear-diag2R-LTRB-r369596v17-alignOnRealGeom-2MEvts.png");
	xyl1b->Draw("colz");
	MyC.Print("xNear-yNear-diag1R-LBRT-cut3-r369596v17-alignOnRealGeom-2MEvts.pdf");
	MyC.Print("xNear-yNear-diag1R-LBRT-cut3-r369596v17-alignOnRealGeom-2MEvts.png");
	xyl2b->Draw("colz");
	MyC.Print("xNear-yNear-diag2R-LTRB-cut3-r369596v17-alignOnRealGeom-2MEvts.pdf");
	MyC.Print("xNear-yNear-diag2R-LTRB-cut3-r369596v17-alignOnRealGeom-2MEvts.png");
}
