{
 TFile f("digiHistosT2-4800kEv-r585ZB.root");
 TCanvas MyC("MyC","",4000,4000);
// MyC.Divide(3,3);
 auto c0=f.Get<TH2D>("chLEtot_0;1");
 auto c1=f.Get<TH2D>("chLEtot_1;1");
 auto c2=f.Get<TH2D>("chLEtot_2;1");
 auto c3=f.Get<TH2D>("chLEtot_3;1");
 auto c4=f.Get<TH2D>("chLEtot_4;1");
 auto c5=f.Get<TH2D>("chLEtot_5;1");
 auto c6=f.Get<TH2D>("chLEtot_6;1");
 auto c7=f.Get<TH2D>("chLEtot_7;1");
 auto c8=f.Get<TH2D>("chLEtot_8;1");
 auto p0=c0->ProfileX();
 auto p1=c1->ProfileX();
 auto p2=c2->ProfileX();
 auto p3=c3->ProfileX();
 auto p4=c4->ProfileX();
 auto p5=c5->ProfileX();
 auto p6=c6->ProfileX();
 auto p7=c7->ProfileX();
 auto p8=c8->ProfileX();
 p0->GetYaxis()->SetRangeUser(-5.,100.);
 p0->SetLineColor(kRed);
 p1->GetYaxis()->SetRangeUser(-5.,100.);
 p1->SetLineColor(kGreen);
 p2->GetYaxis()->SetRangeUser(-5.,100.);
 p2->SetLineColor(kBlue);
 p3->GetYaxis()->SetRangeUser(-5.,100.);
 p3->SetLineColor(kRed);
 p4->GetYaxis()->SetRangeUser(-5.,100.);
 p4->SetLineColor(kGreen);
 p5->GetYaxis()->SetRangeUser(-5.,100.);
 p5->SetLineColor(kBlue);
 p6->GetYaxis()->SetRangeUser(-5.,100.);
 p6->SetLineColor(kRed);
 p7->GetYaxis()->SetRangeUser(-5.,100.);
 p8->SetLineColor(kGreen);
 p8->GetYaxis()->SetRangeUser(-5.,100.);
 p8->SetLineColor(kBlue);
 p3->Draw();
 p4->Draw("same");
 p5->Draw("same");
 TLegend lg(0.5,0.7,0.78,0.9);
 lg.AddEntry(p3,"Ch. 3","lep");
 lg.AddEntry(p4,"Ch. 4","lep");
 lg.AddEntry(p5,"Ch. 5","lep");
 lg.Draw();
 MyC.Print("pfxT2-channels-3to5-LE-vs-tot.pdf");
 MyC.Print("pfxT2-channels-3to5-LE-vs-tot.eps");
 MyC.Print("pfxT2-channels-3to5-LE-vs-tot.png");
 MyC.Clear();
 p6->Draw();
 p7->Draw("same");
 p8->Draw("same");
 TLegend lk(0.5,0.7,0.78,0.9);
 lk.AddEntry(p6,"Ch. 6","lep");
 lk.AddEntry(p7,"Ch. 7","lep");
 lk.AddEntry(p8,"Ch. 8","lep");
 lk.Draw();
 MyC.Print("pfxT2-channels-6to8-LE-vs-tot.pdf");
 MyC.Print("pfxT2-channels-6to8-LE-vs-tot.eps");
 MyC.Print("pfxT2-channels-6to8-LE-vs-tot.png");
}
