{
 TFile f("digiHistosT2-4800kEv-r585ZB.root");
 TCanvas MyC("MyC","",2000,5000);
 MyC.Divide(2,5);
 auto c0=f.Get<TH2D>("chLEtot_54;1");
 auto c1=f.Get<TH2D>("chLEtot_55;1");
 auto c2=f.Get<TH2D>("chLEtot_56;1");
 auto c3=f.Get<TH2D>("chLEtot_57;1");
 auto c4=f.Get<TH2D>("chLEtot_58;1");
 auto c5=f.Get<TH2D>("chLEtot_59;1");
 auto c6=f.Get<TH2D>("chLEtot_60;1");
 auto c7=f.Get<TH2D>("chLEtot_61;1");
 auto c8=f.Get<TH2D>("chLEtot_62;1");
 auto c9=f.Get<TH2D>("chLEtot_63;1");
 MyC.cd(1);
 gPad->SetLogz();
 c0->Draw("colz");
 MyC.cd(2);
 gPad->SetLogz();
 c1->Draw("colz");
 MyC.cd(3);
 gPad->SetLogz();
 c2->Draw("colz");
 MyC.cd(4);
 gPad->SetLogz();
 c3->Draw("colz");
 MyC.cd(5);
 gPad->SetLogz();
 c4->Draw("colz");
 MyC.cd(6);
 gPad->SetLogz();
 c5->Draw("colz");
 MyC.cd(7);
 gPad->SetLogz();
 c6->Draw("colz");
 MyC.cd(8);
 gPad->SetLogz();
 c7->Draw("colz");
 MyC.cd(9);
 gPad->SetLogz();
 c8->Draw("colz");
 MyC.cd(10);
 gPad->SetLogz();
 c9->Draw("colz");
 MyC.Print("T2-channels-54to63-LE-vs-tot.pdf");
 MyC.Print("T2-channels-54to63-LE-vs-tot.eps");
 MyC.Print("T2-channels-54to63-LE-vs-tot.png");
}